language: go

go:
  - tip
  - 1.15.x

env:
  - GO111MODULE=on

before_script:
  - go get -u -v github.com/smallnest/nettrace

script:
  - go test -v ./...

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
